version: "3"
services:
  web:
    container_name: unpkg-web-dev
    command: ["bash", "-c", "yarn run watch & source .env && node server.js"]
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_URL: "redis://redis_cache:6379"
      NODE_ENV: "development"
    volumes:
      - .:/usr/src/app
    ports:
      - "8081:5000"
    depends_on:
      - redis_cache

  redis_cache:
    image: redis
